language: python
python:
  - "3.8"
services:
  - postgresql
before_install:
  - pip install poetry
  - pip install coveralls
  - echo "POSTGRES_HOST=localhost" > .env.local
install:
  - poetry install
  - python manage.py migrate
script:
  - pytest --cov=keep_fm/
after_success:
  - coveralls
