language: python
python:
  - "3.8"
services:
  - postgresql
env:
  - POSTGRES_HOST=postgres://postgres@localhost/postgres
before_install:
  - pip install poetry
install:
  - poetry install
  - python manage.py migrate
script:
  - pytest --cov=keep_fm/
after_success:
  - coveralls
