language: python
python:
  - "3.8"
services:
  - postgresql
before_install:
  - pip install poetry
  - psql -c 'create database postgres;' -U postgres
install:
  - poetry install
  - python manage.py migrate
script:
  - pytest --cov=keep_fm/
after_success:
  - coveralls
