language: python
python:
  - "3.9"
services:
  - postgresql
before_install:
  - pip install coveralls
  - echo "POSTGRES_HOST=localhost" > .env.local
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python manage.py migrate
script:
  - pytest --cov=keep_fm/
after_success:
  - coveralls
