version: '3.7'

services:
  celery:
    container_name: keep_fm_worker
    command: celery -A keep_fm.celery worker -B -l info
    depends_on:
      - redis
      - db
    env_file:
      - .env
      - .env.local
    image: keep-fm-django
    volumes:
      - .:/app
  db:
    image: postgres:12.2-alpine
    container_name: keep_fm_postgres
    env_file:
      - .env
      - .env.local
    volumes:
      - pgdata:/var/lib/postgresql/data
  django:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: gunicorn keep_fm.wsgi:application --bind 0.0.0.0:8000 --workers ${GUNICORN_WORKERS} --timeout ${GUNICORN_TIMEOUT}
    container_name: keep_fm_django
    depends_on:
      - db
    env_file:
      - .env
      - .env.local
    image: keep-fm-django
    ports:
      - "${DJANGO_PORT}:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - ./static:/app/static
  redis:
    container_name: keep_fm_redis
    image: redis:5.0.8-alpine
volumes:
  pgdata:
  static: