# Generated by Django 3.0.6 on 2020-05-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0003_auto_20200513_1850"),
        ("scrobbles", "0001_initial"),
        ("users", "0002_auto_20200513_1845"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tracks",
            field=models.ManyToManyField(
                related_name="listeners",
                through="scrobbles.Scrobble",
                to="tracks.Track",
            ),
        ),
    ]
