# Generated by Django 3.0.6 on 2020-05-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0003_auto_20200513_1850"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="spotify_uri",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Spotify API URI"
            ),
        ),
    ]
