# Generated by Django 3.0.6 on 2020-06-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0004_track_spotify_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
