# Generated by Django 3.0.6 on 2020-06-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0005_track_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="slug",
            field=models.SlugField(blank=True, max_length=2048, null=True),
        ),
    ]
