# Generated by Django 3.0.6 on 2020-05-13 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0003_auto_20200513_1850"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scrobbles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="scrobble_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Scrobble date"
            ),
        ),
        migrations.AlterField(
            model_name="scrobble",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scrobbles",
                to="tracks.Track",
                verbose_name="Track",
            ),
        ),
        migrations.AlterField(
            model_name="scrobble",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scrobbles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Listener",
            ),
        ),
    ]
